[DRAFT]Remove the heap allocation from non-single queues
smol-rs/concurrent-queue pull request #53
Opened 2023-11-13 23:39 UTC by scirin

#52 
Draft

2023-11-14 02:01 UTC, notgull requested changes
Overall looks good to me, but I'd like a second opinion.

@smol-rs/admins Thoughts?

2023-11-14 02:01 UTC, notgull commented on src/lib.rs
> +// use alloc::boxed::Box;
Remove this comment

2023-11-14 02:01 UTC, notgull commented on src/lib.rs
>  enum Inner<T> {
Add `#[allow(clippy::large-enum-variant)]` to this enum to silence clippy.

2023-11-15 22:23 UTC, fogti approved these changes

2023-11-15 22:26 UTC, fogti commented
NOTE: use squash merging / better commit message.

2023-11-16 02:05 UTC, notgull approved these changes

2023-11-16 02:08 UTC, merged